spring:
  application:
    name: toeic-ai-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/toeic_ai_platform
    username: postgres
    password: 2211063

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true